name: CI playground tests for GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  allure_version: 2.29.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/checkout@v4
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Build and Test with Maven
        run: mvn -B clean test
        env:
          DISPLAY: :99

      - name: Verify test results
        run: |
          ls -la target/allure-results
          ls -la target/surefire-reports
          [ -n "$(ls -A target/allure-results)" ] || { echo "Allure results directory is empty"; exit 1; }

      - name: Attach screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots


      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Check Allure results
        run: ls -la target/allure-results


      - name: Publish Allure report to Github Pages
        if: ${{ success() || failure() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload Allure HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report



