name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Run UI tests
        run: |
          mvn test 
          # Additional checks
          test -f target/surefire-reports/TEST-*.xml || echo "No test results found"

      - name: Verify test results
        run: |
          ls -la target/allure-results
          ls -la target/surefire-reports
          [ -n "$(ls -A target/allure-results)" ] || { echo "Allure results directory is empty"; exit 1; }


      - name: Attach screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Check Allure results
        run: ls -la target/allure-results

      - name: Publish Allure report to Github Pages
        if: ${{ success() || failure() }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history


