name: Java CI with Selenide and Allure

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package

      - name: Collect test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            target/selenide-screenshots/
            target/surefire-reports/
            target/allure-results/
            ./video/
          retention-days: 3

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          ignore_unknown_options: true

      - name: Deploy Allure Report
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/allure-report
          KEEP_HISTORY: true