name: Java CI with Selenide

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Selenide Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        run: |
          # Устанавливаем уникальный каталог для данных пользователя
          export SELENIDE_REMOTE="--user-data-dir=/tmp/chrome-profile-$GITHUB_RUN_ID"
          export SELENIDE_DOWNLOAD_FOLDER=/tmp/chrome-downloads-$GITHUB_RUN_ID
          
          mvn clean test -Pci \
            -Dselenide.headless=true \
            -Dselenide.browserSize=1920x1080 \
            -Dselenide.remote="$SELENIDE_REMOTE" \
            -Dselenide.downloadsFolder="$SELENIDE_DOWNLOAD_FOLDER"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/allure-results/